### ISSUE TITLE
Link on readme dont open

### ISSUE THREAD

**Issue by mauriciocoruja** [guilfer-dev/no-canvas-snake#4]
Trying to access the game by the link on readme a 404 error occours
![githuberror](https://user-images.githubusercontent.com/38763395/138260649-5c3efb91-7862-40a4-808c-f484bbe7dec6.png)

**Comment by guilfer-dev** [comment]
Fixed

**Comment by guilfer-dev** [comment]
> Trying to access the game by the link on readme a 404 error occours ![githuberror](https://user-images.githubusercontent.com/38763395/138260649-5c3efb91-7862-40a4-808c-f484bbe7dec6.png)

Fixed
